### ISSUE TITLE
TaskScheduler.run

### ISSUE THREAD

**Issue by JetaimeNotLove** [lwl1989/timing#1]
你好， 在TaskScheduler.run 方法中，for循环存在的意义是什么？最后加了break，可见for循环只执行了一次

**Comment by lwl1989** [comment]
```
for{
    for {
        select{
        }
        break;
    }
}
```
代码结构应该是这样

这块其实可以看成是
```
for{
    action()
}
```
其实就是保证程序在执行，select做阻塞，一次只执行第二个for中的一个select

**Comment by JetaimeNotLove** [comment]
了解，不过不加for会存在跳过select的情况吗，我看你的没有加default呀

**Comment by lwl1989** [comment]
假如没有default，那么在就是指没有符合条件的任务得到执行，就会在此阻塞

另外，一般default会不写处理，因为select中的default子句总是可运行的，会很消耗CPU资源
