### ISSUE TITLE
老哥bug一大堆 编译都过不了 你确定能用？

### ISSUE THREAD

**Issue by AdamTyn** [lwl1989/timing#2]
老哥bug一大堆 编译都过不了 你确定能用？

**Comment by lwl1989** [comment]
请提供下截图，test是通过的，不知道是哪里没编译通过

**Comment by AdamTyn** [comment]
老哥 如果我说我的IDE欺骗了我 你会不会砍我

我编译的时候发现很多方法没有写实例在前面

> 譬如 task.GetJob()
> 
> 在我编辑器里面变成了GetJob()

没有前面的task

> 我刚刚用compare工具打开
> 
> 发现是有改动的

我发4我是没有该过的

现在我回退版本以后

发现才发现上面提到的问题

**Comment by AdamTyn** [comment]
你看
![image](https://user-images.githubusercontent.com/29447491/65655530-1fad4c80-e04f-11e9-9bf0-0266c7ac1aa7.png)

**Comment by AdamTyn** [comment]
我查看localhistory 发现是我移动文件夹以后 ide就自动去掉了方法前面那一截
难受

**Comment by lwl1989** [comment]
老哥不要慌

😄
