### ISSUE TITLE
自定义任务，如何传入带参函数

### ISSUE THREAD

**Issue by dreamer2q** [lwl1989/timing#5]
## 起因

今天更新了一下包，发现你的包改动很大，导致之前写的代码无法编译通过。

还有就是之前你的包，似乎有点bug，就是我指定`RunTime`,`Spacing`,`EndTime`，
发现并没有按照`Spacing`间隔执行，往往是只执行一次就没了。
但是指定`Number`就没有这个问题。

## 问题

![image](https://user-images.githubusercontent.com/56211747/72777664-643da300-3c51-11ea-83df-149d393fa2e8.png)

我需要传入一个`s`参数，如何避免上述写法?

**Comment by dreamer2q** [comment]
太鬼畜了，你的注释都没有更新:neutral_face:

**Comment by lwl1989** [comment]
readme里面写了  tips: 间隔时间需要严格按照nanoSecond计算

**Comment by lwl1989** [comment]
![image](https://user-images.githubusercontent.com/13486464/72778870-1dea4300-3c55-11ea-89ca-b7a883ebaca4.png)

**Comment by lwl1989** [comment]
兄弟你拉master分支吧，或者go mod指定v1.1.1的版本。 新旧版本是有部分不兼容。

**Comment by lwl1989** [comment]
兄弟你拉master分支吧，或者go mod指定v1.2.2的版本。 新旧版本是有部分不兼容。
以后的release都是v2开始了
